Update typing_test.py
removed the second positional argument in  calculated_speed = self.calculate_speed(typed_text, original_text), since it is not needed.
Otherwise you get this error:
TypeError: calculate_speed() takes 2 positional arguments but 3 were given